# Generated by Django 5.0.9 on 2026-06-25 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("explain", models.TextField(blank=True, max_length=350)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, null=True)),
                ("form", models.CharField(max_length=100, null=True)),
                ("chapter", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "given_by",
                    models.CharField(
                        blank=True, default="Unknown", max_length=50, null=True
                    ),
                ),
                ("question", models.CharField(max_length=600)),
                ("answer", models.CharField(max_length=50, null=True)),
                ("form_info", models.CharField(max_length=200, null=True)),
                ("is_saved", models.BooleanField(default=False)),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fomulas",
                        to="formulas.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
