# Generated by Django 5.2.10 on 2026-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100, null=True)),
                ('chapter', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200)),
                ('given_by', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=600)),
            ],
        ),
    ]
