# Generated by Django 5.2.10 on 2026-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
