# Generated by Django 5.1.3 on 2026-06-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="exam_tag",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("jee", "JEE"),
                    ("neet", "NEET"),
                    ("both", "Both"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
