# Generated by Django 5.2.10 on 2026-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_formula_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
