# Generated by Django 5.1.3 on 2026-06-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0003_alter_formula_exam_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="simulation_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
