# Generated by Django 5.2.10 on 2026-01-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_formula_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='solve',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
