# Generated by Django 5.2.10 on 2026-01-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_formula_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='correct_answer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='solve',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
