# Generated by Django 5.1.3 on 2026-06-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0004_category_simulation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="given_by",
            field=models.CharField(
                blank=True, default="Derived", max_length=50, null=True
            ),
        ),
    ]
