# Generated by Django 5.2.10 on 2026-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0005_formula_correct_answer_alter_formula_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='form_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
