# Generated by Django 5.1.3 on 2026-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0005_alter_formula_given_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="PYQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "exam",
                    models.CharField(
                        choices=[
                            ("JEE", "JEE"),
                            ("NEET", "NEET"),
                            ("BOTH", "JEE/NEET"),
                        ],
                        default="JEE",
                        max_length=10,
                    ),
                ),
                ("formula_name", models.CharField(max_length=150)),
                ("formula_exp", models.CharField(max_length=200)),
                ("times_asked", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
    ]
