# Generated by Django 5.2.10 on 2026-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0006_formula_form_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='correct_answer',
            field=models.CharField(null=True),
        ),
    ]
