# Generated by Django 5.1.3 on 2026-07-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0006_pyq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="explain",
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
