# Generated by Django 5.2.10 on 2026-01-13 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0007_alter_formula_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('explain', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fomulas', to='formulas.category'),
        ),
    ]
