# Generated by Django 5.1.3 on 2026-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0007_alter_category_explain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="answer",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
