# Generated by Django 5.2.10 on 2026-01-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0008_category_formula_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='formula',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
