# Generated by Django 5.2.10 on 2026-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0009_alter_category_options_formula_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='form_info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
