# Generated by Django 5.2.10 on 2026-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0010_alter_formula_form_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='explain',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
