# Generated by Django 5.1.3 on 2026-07-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0011_alter_formula_chapter_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="formulas.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="formula",
            name="given_by",
            field=models.CharField(blank=True, default="Derived", max_length=100),
        ),
    ]
