# Generated by Django 5.2.10 on 2026-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0011_formula_image_alter_category_explain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
