# Generated by Django 5.2.10 on 2026-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0012_alter_formula_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="image",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
