# Generated by Django 5.1.3 on 2026-07-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0012_alter_formula_chapter_alter_formula_given_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="given_by",
            field=models.CharField(blank=True, default="Derived", max_length=200),
        ),
    ]
