# Generated by Django 5.2.10 on 2026-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0013_alter_formula_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="explanation",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
