# Generated by Django 5.1.3 on 2026-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0014_alter_formula_given_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="derivation_image",
            field=models.ImageField(blank=True, null=True, upload_to="derivation/"),
        ),
    ]
