# Generated by Django 5.2.10 on 2026-01-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0014_formula_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="image",
            field=models.ImageField(default=False, null=True, upload_to="posts"),
        ),
    ]
