# Generated by Django 5.1.3 on 2026-07-14 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0015_formula_derivation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="derivation_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="derivation/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
