# Generated by Django 5.2.10 on 2026-01-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0015_alter_formula_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="explanation",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
