# Generated by Django 5.1.3 on 2026-07-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0016_alter_formula_derivation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="common_mistakes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formula",
            name="mnemonic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formula",
            name="worked_example",
            field=models.TextField(blank=True, null=True),
        ),
    ]
