# Generated by Django 5.0.9 on 2026-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0016_alter_formula_explanation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formula",
            name="image",
        ),
        migrations.AlterField(
            model_name="formula",
            name="correct_answer",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
