# Generated by Django 5.1.3 on 2026-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0017_formula_common_mistakes_formula_mnemonic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="answer",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="formula",
            name="example",
            field=models.TextField(blank=True, null=True),
        ),
    ]
