# Generated by Django 5.1.3 on 2026-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0018_alter_formula_answer_alter_formula_example"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="desmos_graph_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
