# Generated by Django 5.1.3 on 2026-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0018_formula_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="given_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
