# Generated by Django 5.1.3 on 2026-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0019_formula_desmos_graph_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="diagram_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
