# Generated by Django 5.1.3 on 2026-06-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0020_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="given_by",
            field=models.CharField(
                blank=True, default="Unknown", max_length=50, null=True
            ),
        ),
    ]
