# Generated by Django 5.1.3 on 2026-07-24 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0020_formula_diagram_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="sim_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="sim_video/thumbnail/"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="sim_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="sim_video/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm"]
                    )
                ],
            ),
        ),
    ]
