# Generated by Django 5.1.3 on 2026-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0021_chapter_sim_thumbnail_chapter_sim_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="sim_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
