# Generated by Django 5.1.3 on 2026-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0021_alter_formula_given_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
