# Generated by Django 5.1.3 on 2026-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0022_alter_formula_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="explanation",
            field=models.ImageField(blank=True, null=True, upload_to="posts"),
        ),
        migrations.AlterField(
            model_name="formula",
            name="solve",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
