# Generated by Django 5.1.3 on 2026-07-25 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0023_simpleuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="diagram_url",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="diagram/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
