# Generated by Django 5.1.3 on 2026-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0023_alter_formula_explanation_alter_formula_solve"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
