# Generated by Django 5.1.3 on 2026-06-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0024_formula_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formula",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fomulas",
                to="formulas.category",
            ),
        ),
    ]
