# Generated by Django 5.1.3 on 2026-06-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0025_alter_formula_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
