# Generated by Django 5.1.3 on 2026-07-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0026_chapter_is_premium_chapter_price_inr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
