# Generated by Django 5.1.3 on 2026-07-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0027_simpleuser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formula",
            name="is_saved",
        ),
        migrations.RemoveField(
            model_name="formula",
            name="session_key",
        ),
        migrations.CreateModel(
            name="SavedFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulas.formula",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_formulas",
                        to="formulas.simpleuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "formula")},
            },
        ),
    ]
