# Generated by Django 5.1.3 on 2026-08-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulas",
            "0028_remove_formula_is_saved_remove_formula_session_key_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_key",
                    models.CharField(
                        choices=[
                            ("jee_main_1", "JEE Main Session 1"),
                            ("jee_main_2", "JEE Main Session 2"),
                            ("jee_advanced", "JEE Advanced"),
                            ("neet", "NEET"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
            ],
            options={
                "ordering": ["exam_date"],
            },
        ),
    ]
