# Generated by Django 5.1.3 on 2026-08-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0029_examdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaConstant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constants",
                        to="formulas.formula",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("expr", models.CharField(max_length=200)),
                ("is_solvable", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_variables",
                        to="formulas.formula",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
