# Generated by Django 5.1.3 on 2026-08-08 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0030_formulaconstant_formulavariable"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                ("scenario_title", models.CharField(max_length=200)),
                ("scenario_story", models.TextField()),
                ("hint", models.CharField(blank=True, max_length=255, null=True)),
                ("correct_formula_name", models.CharField(max_length=100)),
                ("correct_formula_latex", models.CharField(max_length=100)),
                ("wrong_option_1", models.CharField(max_length=100)),
                ("wrong_option_2", models.CharField(max_length=100)),
                ("wrong_option_3", models.CharField(max_length=100)),
                ("explanation", models.TextField()),
            ],
        ),
    ]
