# Generated by Django 5.1.3 on 2026-08-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0031_dailychallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedchapter",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="formulas.simpleuser",
            ),
        ),
    ]
