# Generated by Django 5.1.3 on 2026-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0032_alter_purchasedchapter_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
