# Generated by Django 5.1.3 on 2026-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0034_alter_formula_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="razorpay_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
