# Generated by Django 5.1.3 on 2026-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0035_chapter_razorpay_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="conceptual_overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formula",
            name="jee_neet_exam_tips",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formula",
            name="real_world_applications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formula",
            name="step_by_step_derivation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
