# Generated by Django 5.1.3 on 2026-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0036_formula_conceptual_overview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, default="JEE / NEET Prep", max_length=100, null=True
                    ),
                ),
                (
                    "read_time",
                    models.CharField(
                        blank=True, default="5 min read", max_length=50, null=True
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
