# Generated by Django 5.1.3 on 2026-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0038_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="related_formula_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
