# Generated by Django 5.1.3 on 2026-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0039_article_related_formula_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="faqs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
